# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tomcats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TomcatGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('description_html', models.BooleanField(default=False)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tomcats.Server')),
            ],
        ),
        migrations.CreateModel(
            name='TomcatInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('description_html', models.BooleanField(default=False)),
                ('tomcatGroup', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tomcats.TomcatGroup')),
            ],
        ),
    ]
