# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomcats', '0002_tomcatgroup_tomcatinstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='tomcatinstance',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
