# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomcats', '0003_tomcatinstance_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tomcatinstance',
            name='auto_refresh_build_info',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tomcatinstance',
            name='build_info_refresh_interval',
            field=models.IntegerField(default=5, help_text='in minutes'),
        ),
    ]
