# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 10:36
from __future__ import unicode_literals

import base.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionEnvironment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=100)),
                ('executablePath', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('arguments', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('scriptFile', models.FileField(upload_to=base.models.user_dir_path)),
                ('executableEnvironment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.ExecutionEnvironment')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.Script'),
        ),
    ]
