# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 08:44
from __future__ import unicode_literals

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20170130_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='scriptFile',
            field=models.FileField(upload_to=base.models.script_file_path),
        ),
    ]
